version: '3.8'

services:
  mysql-dev-hibernate-hm:
    image: mysql:8.0
    container_name: hibernate
    cap_add:
      - SYS_NICE
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: hibernate-hw
    ports:
      - "6605:3306"
    volumes:
        - db:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    db:
      driver: local